quarkus.banner.enabled=false
quarkus.log.level=WARN

# Native image config
quarkus.native.auto-service-loader-registration=true
quarkus.native.resources.includes=org/jline/utils/**,org/jline/terminal/**,META-INF/services/org/jline/terminal/provider/*
quarkus.native.additional-build-args=--initialize-at-run-time=org.jline.nativ,\
  --exclude-config,org\\.jline,/META-INF/native-image/.*
