#!/usr/bin/env python3
"""Trim the site's fonts to what the first screen needs, and write their @font-face rules.

Each family ships three files, and a browser downloads only those a page has characters for:
  <family>-core.woff2       ASCII plus the punctuation the site uses: the small file every
                            page needs, preloaded. Every weight is kept: cutting the weight
                            axis to the CSS's range saves ~11 KB more over the three families,
                            but re-interpolating it shifts the anti-aliasing of the text.
  <family>-latin.woff2      Google Fonts' latin file, unchanged, for the rest of its range
                            (accented letters and the like), so no character loses its font.
  <family>-latin-ext.woff2  Google Fonts' latin-ext file, unchanged.

Rerun after replacing a font or when the site starts using a new punctuation mark often:
    python3 site/subset-fonts.py
It rewrites the block between the fonts:begin/fonts:end markers in style.css. Needs fontTools
with brotli: dnf install python3-fonttools python3-brotli.
"""
import os
import re

from fontTools import subset
from fontTools.ttLib import TTFont

SITE = os.path.dirname(os.path.abspath(__file__))
FONTS = os.path.join(SITE, "vendor", "fonts")

# family name, file prefix, the weight range the CSS uses
FAMILIES = [
    ("Inter", "inter-v20", (400, 600)),
    ("JetBrains Mono", "jetbrains-mono-v24", (400, 500)),
    ("Space Grotesk", "space-grotesk-v22", (500, 700)),
]

# Beyond ASCII: nbsp, ©, ·, ×, dashes, curly quotes, bullet, ellipsis, arrows, ∎ (where the font has them).
CORE_EXTRA = [0xA0, 0xA9, 0xB7, 0xD7, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026,
              0x2190, 0x2191, 0x2192, 0x2193, 0x220E]

CONTROLS = set(range(0x00, 0x20)) | set(range(0x7F, 0xA0))

# Google Fonts' ranges for the files it serves.
LATIN = ("U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, "
         "U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD")
LATIN_EXT = ("U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, "
             "U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, "
             "U+A720-A7FF")


def parse_range(r):
    points = set()
    for part in r.split(","):
        lo, _, hi = part.strip()[2:].partition("-")
        points.update(range(int(lo, 16), int(hi or lo, 16) + 1))
    return points


def format_range(points):
    points, runs = sorted(points), []
    for p in points:
        if runs and p == runs[-1][1] + 1:
            runs[-1][1] = p
        else:
            runs.append([p, p])
    return ", ".join(f"U+{a:04X}" if a == b else f"U+{a:04X}-{b:04X}" for a, b in runs)


def make_core(prefix):
    src = os.path.join(FONTS, prefix + "-latin.woff2")
    font = TTFont(src)
    cmap = font.getBestCmap()
    core = {c for c in list(range(0x20, 0x7F)) + CORE_EXTRA if c in cmap}
    opts = subset.Options()
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=core)
    sub.subset(font)
    font.flavor = "woff2"
    font.save(os.path.join(FONTS, prefix + "-core.woff2"))
    return core


def face(family, prefix, weights, part, unicode_range):
    return (f'@font-face {{\n  font-family: "{family}";\n  font-style: normal;\n'
            f"  font-weight: {weights[0]} {weights[1]};\n  font-display: swap;\n"
            f'  src: url("vendor/fonts/{prefix}-{part}.woff2") format("woff2");\n'
            f"  unicode-range: {unicode_range};\n}}\n")


def main():
    faces = []
    for family, prefix, weights in FAMILIES:
        core = make_core(prefix)
        faces.append(face(family, prefix, weights, "latin-ext", LATIN_EXT))
        # Control characters (newlines and tabs in code blocks) are never drawn, but a range that
        # lists them may still make a browser fetch the file: keep them in the core file's range.
        core_range = core | CONTROLS
        faces.append(face(family, prefix, weights, "latin", format_range(parse_range(LATIN) - core_range)))
        faces.append(face(family, prefix, weights, "core", format_range(core_range)))
    css_path = os.path.join(SITE, "style.css")
    css = open(css_path, encoding="utf-8").read()
    block = "/* fonts:begin (generated by subset-fonts.py) */\n" + "\n".join(faces) + "/* fonts:end */"
    css, n = re.subn(r"/\* fonts:begin.*?/\* fonts:end \*/", lambda _: block, css, flags=re.S)
    if n != 1:
        raise SystemExit("style.css: expected one fonts:begin/fonts:end block")
    open(css_path, "w", encoding="utf-8").write(css)


if __name__ == "__main__":
    main()
