package dev.incusspawn.proxy;

import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.StandardWatchEventKinds;
import java.nio.file.WatchKey;
import java.util.Set;
import java.util.concurrent.TimeUnit;

/**
 * Watches {@code ~/.config/incus-spawn/} for changes to CA certificates and
 * config, triggering a proxy reload on relevant events. A 500ms debounce
 * coalesces rapid events from directory restores or editor save-and-rename.
 * <p>
 * Only {@code ca.crt}, {@code ca.key}, and {@code config.yaml} are watched.
 * {@code certs/} is excluded — leaf certs are generated by the proxy itself
 * and watching them would create a feedback loop.
 */
public class ConfigWatcher {

    private static final long DEBOUNCE_MS = 500;
    private static final Set<String> WATCHED_FILES = Set.of("ca.crt", "ca.key", "config.yaml");

    private final Path configDir;
    private final Runnable onReload;
    private volatile boolean running = true;

    public ConfigWatcher(Path configDir, Runnable onReload) {
        this.configDir = configDir;
        this.onReload = onReload;
    }

    public void start() {
        var thread = new Thread(this::watchLoop, "config-watcher");
        thread.setDaemon(true);
        thread.start();
    }

    public void stop() {
        running = false;
    }

    private void watchLoop() {
        try (var watchService = FileSystems.getDefault().newWatchService()) {
            configDir.register(watchService,
                    StandardWatchEventKinds.ENTRY_CREATE,
                    StandardWatchEventKinds.ENTRY_MODIFY,
                    StandardWatchEventKinds.ENTRY_DELETE);

            while (running) {
                WatchKey key;
                try {
                    key = watchService.poll(1, TimeUnit.SECONDS);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    return;
                }
                if (key == null) continue;

                boolean relevant = false;
                for (var event : key.pollEvents()) {
                    if (event.kind() == StandardWatchEventKinds.OVERFLOW) continue;
                    var path = (Path) event.context();
                    if (path != null && WATCHED_FILES.contains(path.toString())) {
                        relevant = true;
                    }
                }
                if (!key.reset()) break;

                if (relevant) {
                    Thread.sleep(DEBOUNCE_MS);
                    // Drain events that arrived during the debounce window
                    WatchKey drainKey;
                    while ((drainKey = watchService.poll()) != null) {
                        drainKey.pollEvents();
                        drainKey.reset();
                    }
                    try {
                        onReload.run();
                    } catch (Exception e) {
                        System.err.println("Config reload failed: " + e.getMessage());
                        ProxyLog.error("Config reload failed: " + e.getMessage());
                    }
                }
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        } catch (Exception e) {
            if (running) {
                System.err.println("Config watcher failed: " + e.getMessage());
                ProxyLog.error("Config watcher failed: " + e.getMessage());
            }
        }
    }
}
