package dev.incusspawn.proxy;

import dev.incusspawn.tool.ToolDefLoader;

import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardWatchEventKinds;
import java.nio.file.WatchEvent;
import java.nio.file.WatchKey;
import java.nio.file.WatchService;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/**
 * Watches {@code ~/.config/incus-spawn/} for changes to CA certificates and
 * config, triggering a proxy reload on relevant events. A 500ms debounce
 * coalesces rapid events from directory restores or editor save-and-rename.
 * <p>
 * Only {@code ca.crt}, {@code ca.key}, and {@code config.yaml} are watched there.
 * {@code certs/} is excluded — leaf certs are generated by the proxy itself
 * and watching them would create a feedback loop.
 * <p>
 * The tool definitions in {@code tools/} and under each search path are watched too (#890).
 * Which directories those are follows the config loaded last, re-read on every poll, so a
 * reload that adds a search path starts watching it. A directory that does not exist yet is
 * picked up once it does; an edit made before that still shows as drift on {@code /health}.
 */
public class ConfigWatcher {

    private static final long DEBOUNCE_MS = 500;
    private static final Set<String> WATCHED_FILES = Set.of("ca.crt", "ca.key", "config.yaml");

    private static final WatchEvent.Kind<?>[] KINDS = {
            StandardWatchEventKinds.ENTRY_CREATE,
            StandardWatchEventKinds.ENTRY_MODIFY,
            StandardWatchEventKinds.ENTRY_DELETE};

    private final Path configDir;
    private final Supplier<List<Path>> toolDirs;
    private final Runnable onReload;
    private volatile boolean running = true;

    public ConfigWatcher(Path configDir, Supplier<List<Path>> toolDirs, Runnable onReload) {
        this.configDir = configDir;
        this.toolDirs = toolDirs;
        this.onReload = onReload;
    }

    public void start() {
        var thread = new Thread(this::watchLoop, "config-watcher");
        thread.setDaemon(true);
        thread.start();
    }

    public void stop() {
        running = false;
    }

    private void watchLoop() {
        try (var watchService = FileSystems.getDefault().newWatchService()) {
            var configKey = configDir.register(watchService, KINDS);
            var toolDirKeys = new HashMap<Path, WatchKey>();

            while (running) {
                watchToolDirs(watchService, toolDirKeys);
                WatchKey key;
                try {
                    key = watchService.poll(1, TimeUnit.SECONDS);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    return;
                }
                if (key == null) continue;

                boolean relevant = false;
                for (var event : key.pollEvents()) {
                    if (event.kind() == StandardWatchEventKinds.OVERFLOW) continue;
                    var path = (Path) event.context();
                    if (path == null) continue;
                    if (key == configKey ? WATCHED_FILES.contains(path.toString()) : ToolDefLoader.isToolFile(path)) {
                        relevant = true;
                    }
                }
                // A tool directory that went away is registered again by watchToolDirs if it comes back.
                if (!key.reset() && key == configKey) break;

                if (relevant) {
                    Thread.sleep(DEBOUNCE_MS);
                    // Drain events that arrived during the debounce window
                    WatchKey drainKey;
                    while ((drainKey = watchService.poll()) != null) {
                        drainKey.pollEvents();
                        drainKey.reset();
                    }
                    try {
                        onReload.run();
                    } catch (Exception e) {
                        System.err.println("Config reload failed: " + e.getMessage());
                        ProxyLog.error("Config reload failed: " + e.getMessage());
                    }
                }
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        } catch (Exception e) {
            if (running) {
                System.err.println("Config watcher failed: " + e.getMessage());
                ProxyLog.error("Config watcher failed: " + e.getMessage());
            }
        }
    }

    /**
     * Watch exactly the tool directories of the config loaded last. A key that is no longer
     * valid (its directory was deleted, possibly while events were drained) is dropped, so the
     * directory is registered again once it exists.
     */
    private void watchToolDirs(WatchService watchService, Map<Path, WatchKey> keys) {
        var wanted = Set.copyOf(toolDirs.get());
        for (var it = keys.entrySet().iterator(); it.hasNext(); ) {
            var entry = it.next();
            if (wanted.contains(entry.getKey()) && entry.getValue().isValid()) continue;
            entry.getValue().cancel();
            it.remove();
        }
        for (var dir : wanted) {
            if (keys.containsKey(dir) || !Files.isDirectory(dir)) continue;
            try {
                keys.put(dir, dir.register(watchService, KINDS));
            } catch (IOException e) {
                // Unreadable: retried on the next poll, and its edits still show as drift.
            }
        }
    }
}
