package dev.incusspawn.command;

import dev.incusspawn.RuntimeServices;
import org.aesh.command.CommandDefinition;
import org.aesh.command.CommandResult;

/**
 * Deprecated, to be removed in a later release: {@code isx list -q} (#1036). It stays, hidden,
 * because shell completion scripts generated by older releases call it by name.
 */
@CommandDefinition(
        name = "instances",
        description = "Deprecated, to be removed in a later release: use 'isx list -q'",
        generateHelp = true
)
public class InstancesCommand extends BaseCommand {

    @Override
    protected CommandResult doExecute() throws Exception {
        var list = new ListCommand();
        list.quiet = true;
        list.printListing(RuntimeServices.incus(), System.out, java.time.ZoneId.systemDefault());
        return CommandResult.SUCCESS;
    }
}
